# Generated by Django 2.2.5 on 2019-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepbud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodystatus',
            name='body_fat_rate',
        ),
        migrations.RemoveField(
            model_name='bodystatus',
            name='waistline',
        ),
        migrations.AddField(
            model_name='bodystatus',
            name='BMI_30',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='bodystatus',
            name='Snoring',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='bodystatus',
            name='Irritability',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='bodystatus',
            name='age',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='bodystatus',
            name='alcoholism',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='bodystatus',
            name='day_sleepy',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
